In [38]:
from numpy import array

## DATA PREP

In [40]:
def split_seq(seq, n_steps):
    '''function to split uni seq for LSTM'''
    X, y = [], []

    for i in range(len(seq)):
        end_ix = i + n_steps
        # check if we are beyond the sequence
        if end_ix > len(seq)-1:
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = seq[i:end_ix], seq[end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return array(X), array(y)

In [41]:
# define input sequence
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]

In [42]:
# choose a number of time steps
n_steps = 3

In [43]:
# split into samples
X, y = split_seq(raw_seq, n_steps)

In [44]:
# look at samples
for i in range(len(X)):
    print(X[i], y[i])

[10 20 30] 40
[20 30 40] 50
[30 40 50] 60
[40 50 60] 70
[50 60 70] 80
[60 70 80] 90


## BASIC LSTM

In [46]:
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense

In [47]:
#reshape for LSTM
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))

In [48]:
# define model
model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

In [49]:
model.fit(X, y, epochs=200, verbose=0)

In [50]:
x_input = array([70, 80, 90])
x_input = x_input.reshape((1, n_steps, n_features))
yhat = model.predict(x_input, verbose=0)
print(yhat)

[[102.129944]]


## Stacked LSTM

In [51]:
# define model
# return sequences
model = Sequential()
model.add(LSTM(50, activation='relu', return_sequences=True, input_shape=(n_steps,
n_features)))
model.add(LSTM(50, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

In [52]:
#run model
model.fit(X, y, epochs=200, verbose=0)

In [53]:
#predict
x_input = array([70, 80, 90])
x_input = x_input.reshape((1, n_steps, n_features))
yhat = model.predict(x_input, verbose=0)
print(yhat)

[[103.2988]]
